# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'coyote' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coyote
  pod "Firebase"
  pod "Firebase/Auth"

  target 'coyote-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coyoteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'coyote-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for coyote-tvOS

end
